# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'picklecontrolcenterui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import wmi


_KEYBOARD_CODES = ["Keycode.A",
                   "Keycode.B",
                   "Keycode.C",
                   "Keycode.D",
                   "Keycode.E",
                   "Keycode.F",
                   "Keycode.G",
                   "Keycode.H",
                   "Keycode.I",
                   "Keycode.J",
                   "Keycode.K",
                   "Keycode.L",
                   "Keycode.M",
                   "Keycode.N",
                   "Keycode.O",
                   "Keycode.P",
                   "Keycode.Q",
                   "Keycode.R",
                   "Keycode.S",
                   "Keycode.T",
                   "Keycode.U",
                   "Keycode.V",
                   "Keycode.W",
                   "Keycode.X",
                   "Keycode.Y",
                   "Keycode.Z",
                   "Keycode.ONE",
                   "Keycode.TWO",
                   "Keycode.THREE",
                   "Keycode.FOUR",
                   "Keycode.FIVE",
                   "Keycode.SIX",
                   "Keycode.SEVEN",
                   "Keycode.EIGHT",
                   "Keycode.NINE",
                   "Keycode.TEN"
                   ]

_BUTTON_CODES = [
     "press_buttons(1)",
     "press_buttons(2)",
     "press_buttons(3)",
     "press_buttons(4)",
     "press_buttons(5)",
     "press_buttons(6)",
     "press_buttons(7)",
     "press_buttons(8)",
     "press_buttons(9)",

                 
]
import os
global CODE_PY_FILE
CODE_PY_FILE = "{0}\\code.py".format(os.getcwd())




class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(533, 511)
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ugly.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(0.9)
        Dialog.setStyleSheet("background-color:black;\n"
"border:0px;\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"            alignment: center;\n"
"            background-color:black;\n"
"}\n"
"QTabBar::tab {color: white;background-color:black;\n"
"border-bottom:1px solid green;\n"
"border-right:1px solid green;\n"
"border-left:1px solid green;\n"
"\n"
"font-size:15px;\n"
"}\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(29, 21))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("color:white;\n"
"border:1px solid white;\n"
"border-radius:10px;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:none;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("background-color:black;\n"
"border-radius:1px;")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:gold;\n"
"border:none")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("background-color:black;\n"
"border-radius:1px;")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_5)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"border-radius:10px;\n"
"color:white;\n"
"border:none;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_3.addWidget(self.pushButton_12, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:red;\n"
"border:none")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setStyleSheet("color:rgb(0, 255, 0);\n"
"border:none;")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 3, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_8.setMaximumSize(QtCore.QSize(400, 400))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("color:white;\n"
"border:1px solid white;\n"
"border-radius:10px;")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border:none;\n"
"color:gold;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("background-color:black;\n"
"color:white;\n"
"border:1px solid white;\n"
"border-radius:0px;")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border:none;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color:black;\n"
"color:white;\n"
"border:1px solid white;border-radius:0px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color:black;\n"
"color:white;\n"
"border:1px solid white;border-radius:0px;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.gridLayout_3.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("color:white;\n"
"border:1px solid white;\n"
"border-radius:10px;")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setStyleSheet("background-color:black;\n"
"color:white;\n"
"border:1px solid white;\n"
"border-radius:1px;")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_6)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:gold;\n"
"border:none")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setStyleSheet("background-color:black;\n"
"color:white;\n"
"border:1px solid white;\n"
"border-radius:1px;")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_7)
        self.gridLayout_3.addWidget(self.groupBox_4, 1, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox.setMaximumSize(QtCore.QSize(400, 400))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color:grey;\n"
"border:0px;\n"
"border-radius:10px;alignment:center")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setStyleSheet("alignment:center")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width:1px;\n"
"border-radius: 10px;color:white;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 2, 5, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: blue;\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width:1px;\n"
"border-radius: 10px;color:white;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 2, 6, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_9.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width:1px;\n"
"border-radius: 10px;color:white;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_5.addWidget(self.pushButton_9, 1, 6, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton{\n"
"background-color: green;\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout_5.addWidget(self.pushButton_1, 0, 6, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 1, 5, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color: red;\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width:1px;\n"
"border-radius: 10px;color:white;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_5.addWidget(self.pushButton_8, 2, 4, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"color:white;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 1, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"color:white;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 0, 5, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color: yellow;\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_5.addWidget(self.pushButton_7, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dial_2 = QtWidgets.QDial(self.frame_2)
        self.dial_2.setMinimumSize(QtCore.QSize(40, 40))
        self.dial_2.setMaximumSize(QtCore.QSize(40, 40))
        self.dial_2.setObjectName("dial_2")
        self.horizontalLayout.addWidget(self.dial_2)
        self.dial = QtWidgets.QDial(self.frame_2)
        self.dial.setMinimumSize(QtCore.QSize(40, 40))
        self.dial.setMaximumSize(QtCore.QSize(40, 40))
        self.dial.setStyleSheet("")
        self.dial.setObjectName("dial")
        self.horizontalLayout.addWidget(self.dial)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 2, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 2, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setText("")
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(139, 120))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/images.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(50, 50, 421, 281))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("color:gold")
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.comboBox.currentIndexChanged.connect(self.update_combo_box)
        self.comboBox_3.currentIndexChanged.connect(self.update_combo_box)
        self. pushButton_12.clicked.connect(self.make_changes)


        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pickle GamePad"))
        self.label_3.setText(_translate("Dialog", "       Left-Rotary"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "1-10"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "keypad left / right"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "keypad up / down"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "volume"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "Mouse up/down"))
        self.comboBox_4.setItemText(5, _translate("Dialog", "Mouse left/right"))
        self.label_5.setText(_translate("Dialog", "toggle function"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "1-10"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "keypad left / right"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "keypad up / down"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "volume"))
        self.comboBox_5.setItemText(4, _translate("Dialog", "Mouse up/down"))
        self.comboBox_5.setItemText(5, _translate("Dialog", "Mouse left/right"))
        self.pushButton_12.setText(_translate("Dialog", "Write"))
        self.label_9.setText(_translate("Dialog", "Pickle Device not detected!"))
        self.label_10.setText(_translate("Dialog", "                              V.0.001"))
        self.label_7.setText(_translate("Dialog", "    Selected-Button"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_3.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_3.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_3.setItemText(7, _translate("Dialog", "8"))
        self.comboBox_3.setItemText(8, _translate("Dialog", "9"))
        self.label_8.setText(_translate("Dialog", "Type:"))
        self.comboBox.setItemText(0, _translate("Dialog", "Keyboard"))
        self.comboBox.setItemText(1, _translate("Dialog", "Gamepad Button"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Q"))
        self.label_4.setText(_translate("Dialog", "        Right-Rotary"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "1-10"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "keypad left / right"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "keypad up / down"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "volume"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "Mouse up/down"))
        self.comboBox_6.setItemText(5, _translate("Dialog", "Mouse left/right"))
        self.label_6.setText(_translate("Dialog", "toggle function"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "1-10"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "keypad left / right"))
        self.comboBox_7.setItemText(2, _translate("Dialog", "keypad up / down"))
        self.comboBox_7.setItemText(3, _translate("Dialog", "volume"))
        self.comboBox_7.setItemText(4, _translate("Dialog", "Mouse up/down"))
        self.comboBox_7.setItemText(5, _translate("Dialog", "Mouse left/right"))
        self.pushButton_6.setText(_translate("Dialog", "8"))
        self.pushButton_3.setText(_translate("Dialog", "9"))
        self.pushButton_9.setText(_translate("Dialog", "6"))
        self.pushButton_1.setText(_translate("Dialog", "3"))
        self.pushButton_4.setText(_translate("Dialog", "5"))
        self.pushButton_8.setText(_translate("Dialog", "7"))
        self.pushButton_5.setText(_translate("Dialog", "4"))
        self.pushButton_2.setText(_translate("Dialog", "2"))
        self.pushButton_7.setText(_translate("Dialog", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "GAMEPAD"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1 ) Hopefully made the Ui responsive enough that you can read the text in the drop downs.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2) software now detects raspberry pico device, finds the drive letters and writes diretly to the code.py file in that drive. if it doesnt detect it, it will instead write to the code.py file in the current working directory.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3 ) added analog stick support.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">4 ) </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "PATCH-NOTES"))

        file_lines = []
        loaded_config = []
        def get_drive_info():
                c = wmi.WMI()

                # Query Win32_LogicalDisk to get drive letters and volume names
                logical_disks = {disk.DeviceID: disk.VolumeName for disk in c.Win32_LogicalDisk()}

                # Query Win32_DiskDrive to get physical disk drive information
                drives = c.Win32_DiskDrive()
                drive_info = []
                for drive in drives:
                        drive_name = drive.Caption
                        drive_letter = None
                        for partition in drive.associators("Win32_DiskDriveToDiskPartition"):
                                for logical_disk in partition.associators("Win32_LogicalDiskToPartition"):
                                        drive_letter = logical_disk.DeviceID
                                        break  # Only consider the first logical disk per partition
                        drive_info.append((drive_name, drive_letter))

                return drive_info
                                                                                                                                                        
        drive_info = get_drive_info()
        for drive_name, drive_letter in drive_info:
                print("Drive Name:", drive_name)
                print("Drive Letter:", drive_letter)
                print()
                if drive_name == "Raspberr Pico USB Device":
                        print('got it')
                        
                        print(drive_letter)
                        global CODE_PY_FILE
                        CODE_PY_FILE = "{0}\\code.py".format(drive_letter)
                        self.label_9.setText(_translate("Dialog", "     pickle controller detected!"))
                        self.label_9.setStyleSheet("color:green;\n")


                        break

#############################

        with open(CODE_PY_FILE, 'r+') as f:
                for line in f.readlines():
                        file_lines.append(line)
                
                if '_BUTTON_1_FUNCTIONALITY = "KEYBOARD"\n' in file_lines :
                        loaded_config.append(line)
                        for button in file_lines :
                                if button[0:21] == "_BUTTON_1_KEYPRESS = ":

                                        self.comboBox_2.clear()
                                        self.comboBox_2.addItems(_KEYBOARD_CODES)

                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                if key == button[21:-1]:
                                                        self.comboBox_2.setCurrentIndex(i)
                                                        i+=1
                                                        break
                                                else:
                                                        i+=1
                                                
                if '_BUTTON_1_FUNCTIONALITY = "GAMEPAD"\n' in file_lines:
                                self.comboBox.setCurrentIndex(1)
                                for button in file_lines :

                                        if button[0:-2] == '_BUTTON_1_PRESS = ':
                                                if  self.comboBox.currentIndex() == 1:
                                                        self.comboBox_2.clear()
                                                        i = 0
                                                        for key in _BUTTON_CODES:
                                                                self.comboBox_2.addItems(["{0}".format(key)])
                                                                i+=1
                                                        if int(button[-2]) > 0:
                                                                button_number = int(button[-2]) - 1
                                                                self.comboBox_2.setCurrentIndex(button_number)

                if '_LEFT_ROTARY_FUNCTIONALITY = "NUMKEYS"\n' in file_lines:
                        self.comboBox_4.setCurrentIndex(0)
                
                if '_LEFT_ROTARY_FUNCTIONALITY = "MOUSE_LEFT_RIGHT"\n' in file_lines:
                        self.comboBox_4.setCurrentIndex(1)
                
                if '_LEFT_ROTARY_FUNCTIONALITY = "MOUSE_UP_DOWN"\n' in file_lines:
                        self.comboBox_4.setCurrentIndex(2)
                
                if '_LEFT_ROTARY_FUNCTIONALITY = "VOL_UP_DOWN"\n' in file_lines:
                        self.comboBox_4.setCurrentIndex(3)

                
                if '_RIGHT_ROTARY_FUNCTIONALITY = "NUMKEYS"\n' in file_lines:
                        self.comboBox_6.setCurrentIndex(0)
                
                if '_RIGHT_ROTARY_FUNCTIONALITY = "MOUSE_LEFT_RIGHT"\n' in file_lines:
                        self.comboBox_6.setCurrentIndex(1)
                
                if '_RIGHT_ROTARY_FUNCTIONALITY = "MOUSE_UP_DOWN"\n' in file_lines:
                        self.comboBox_6.setCurrentIndex(2)
                
                if '_RIGHT_ROTARY_FUNCTIONALITY = "VOL_UP_DOWN"\n' in file_lines:
                        self.comboBox_6.setCurrentIndex(3)

    

    def make_changes(self):
            
            selected_button = self.comboBox_3.currentIndex()
            selected_button_functionality = self.comboBox.currentIndex()
            selected_button_press = self.comboBox_2.currentIndex()

            

            if selected_button == 0 :
                    selected_button+=1
            else:
                    selected_button = selected_button + 1

            if selected_button_press == 0 :
                selected_button_press+=1
            else:
                selected_button_press = selected_button_press + 1
            
            file_lines = []

            with open(CODE_PY_FILE, 'r+') as f:
                for line in f.readlines():
                        file_lines.append(line)

            i=0
            if self.comboBox_4.currentIndex() == 0:
                for line in file_lines:
                        if line[0:28] == '_LEFT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY = "NUMKEYS"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_4.currentIndex() == 1:
                for line in file_lines:
                        if line[0:28] == '_LEFT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY = "KEYPAD_LEFT_RIGHT"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_4.currentIndex() == 2:
                for line in file_lines:
                        if line[0:28] == '_LEFT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY = "KEYPAD_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_4.currentIndex() == 3:
                for line in file_lines:
                        if line[0:28] == '_LEFT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY = "VOL_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_4.currentIndex() == 4:
                for line in file_lines:
                        if line[0:28] == '_LEFT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY = "MOUSE_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_4.currentIndex() == 5:
                for line in file_lines:
                        if line[0:28] == '_LEFT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY = "MOUSE_LEFT_RIGHT"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            
                with open(CODE_PY_FILE, 'w+') as f:
                        f.writelines(file_lines)




############################################################
                        
            i=0
            if self.comboBox_5.currentIndex() == 0:
                for line in file_lines:
                        if line[0:35] == '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE = "NUMKEYS"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_5.currentIndex() == 1:
                for line in file_lines:
                        if line[0:35] == '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE = "KEYPAD_LEFT_RIGHT"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_5.currentIndex() == 2:
                for line in file_lines:
                        if line[0:35] == '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE = "KEYPAD_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_5.currentIndex() == 3:
                for line in file_lines:
                        if line[0:35] == '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE = "VOL_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_5.currentIndex() == 4:
                for line in file_lines:
                        if line[0:35] == '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE = "MOUSE_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_5.currentIndex() == 5:
                for line in file_lines:
                        if line[0:35] == '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_LEFT_ROTARY_FUNCTIONALITY_TOGGLE = "MOUSE_LEFT_RIGHT"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            
                with open(CODE_PY_FILE, 'w+') as f:
                        f.writelines(file_lines)


#####################################################
                        

            i=0
            if self.comboBox_6.currentIndex() == 0:
                for line in file_lines:
                        if line[0:29] == '_RIGHT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY = "NUMKEYS"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_6.currentIndex() == 1:
                for line in file_lines:
                        if line[0:29] == '_RIGHT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY = "KEYPAD_LEFT_RIGHT"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_6.currentIndex() == 2:
                for line in file_lines:
                        if line[0:29] == '_RIGHT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY = "KEYPAD_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_6.currentIndex() == 3:
                for line in file_lines:
                        if line[0:29] == '_RIGHT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY = "VOL_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_6.currentIndex() == 4:
                for line in file_lines:
                        if line[0:29] == '_RIGHT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY = "MOUSE_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_6.currentIndex() == 5:
                for line in file_lines:
                        if line[0:29] == '_RIGHT_ROTARY_FUNCTIONALITY =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY = "MOUSE_LEFT_RIGHT"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            
                with open(CODE_PY_FILE, 'w+') as f:
                        f.writelines(file_lines)

##########################
                        
            i=0
            if self.comboBox_7.currentIndex() == 0:
                for line in file_lines:
                        if line[0:36] == '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE = "NUMKEYS"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_7.currentIndex() == 1:
                for line in file_lines:
                        if line[0:36] == '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE = "KEYPAD_LEFT_RIGHT"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_7.currentIndex() == 2:
                for line in file_lines:
                        if line[0:36] == '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE = "KEYPAD_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_7.currentIndex() == 3:
                for line in file_lines:
                        if line[0:36] == '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE = "VOL_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_7.currentIndex() == 4:
                for line in file_lines:
                        if line[0:36] == '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE = "MOUSE_UP_DOWN"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            if self.comboBox_7.currentIndex() == 5:
                for line in file_lines:
                        if line[0:36] == '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE =':
                                i+=1

                                file_lines[i-1] = '_RIGHT_ROTARY_FUNCTIONALITY_TOGGLE = "MOUSE_LEFT_RIGHT"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1

            
                with open(CODE_PY_FILE, 'w+') as f:
                        f.writelines(file_lines)


            if selected_button_functionality == 1:
                i=0
                for line in file_lines:
                        if line[0:26] == '_BUTTON_{0}_FUNCTIONALITY = '.format(selected_button):
                                i+=1

                                file_lines[i-1] = '_BUTTON_{0}_FUNCTIONALITY = "GAMEPAD"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1
                with open(CODE_PY_FILE, 'w+') as f:
                        f.writelines(file_lines)
                
                i=0
                for line in file_lines:
                        if line[0:18] == '_BUTTON_{0}_PRESS = '.format(selected_button):
                                i+=1

                                file_lines[i-1] = '_BUTTON_{0}_PRESS = {1}\n'.format(selected_button, selected_button_press)
                                
                                break
                        else:
                                i+=1
                with open(CODE_PY_FILE, 'w+') as f:
                        f.writelines(file_lines)
        

     

            elif selected_button_functionality == 0:
                i=0
                for line in file_lines:
                        if line[0:26] == '_BUTTON_{0}_FUNCTIONALITY = '.format(selected_button):
                                i+=1

                                file_lines[i-1] = '_BUTTON_{0}_FUNCTIONALITY = "KEYBOARD"\n'.format(selected_button)
                                
                                break
                        else:
                                i+=1
                with open(CODE_PY_FILE, 'w+') as f:
                        f.writelines(file_lines)

                i=0
                for line in file_lines:
                    if line[0:21] == '_BUTTON_{0}_KEYPRESS = '.format(selected_button):
                        i+=1
                        file_lines[i-1] = '_BUTTON_{0}_KEYPRESS = {1}\n'.format(selected_button, self.comboBox_2.currentText())         
                        break
                    else:
                        i+=1
                with open(CODE_PY_FILE, 'w+') as f:
                        f.writelines(file_lines)

            self.update_combo_box()

                        
                                

    def update_combo_box(self):
        file_lines = []
        global CODE_PY_FILE


        with open(CODE_PY_FILE, 'r+') as f:
                for line in f.readlines():
                        file_lines.append(line)

        self.comboBox_2.clear()

        

###########################################################################################################

        if  self.comboBox_3.currentIndex() == 0:
                if self.comboBox.currentIndex() == 1:
                        for button in file_lines :
                                if button[0:-2] == '_BUTTON_1_PRESS = ':
                                        if  self.comboBox.currentIndex() == 1:
                                                self.comboBox_2.clear()
                                                i = 0
                                                for key in _BUTTON_CODES:
                                                        self.comboBox_2.addItems(["{0}".format(key)])
                                                        i+=1
                                                        if int(button[-2]) > 0:
                                                                button_number = int(button[-2]) - 1
                                                                self.comboBox_2.setCurrentIndex(button_number)

                elif self.comboBox.currentIndex() == 0:
                        for button in file_lines :
                                if button[0:21] == "_BUTTON_1_KEYPRESS = ":

                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                self.comboBox_2.addItems(["{0}".format(key)])
                                                i+=1
                                        
                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                if key == button[21:-1]:
                                                        self.comboBox_2.setCurrentIndex(i)
                                                        break
                                                else:
                                                        i+=1
                                        break

###########################################################################################################

        if  self.comboBox_3.currentIndex() == 1:
                if self.comboBox.currentIndex() == 1:
                        for button in file_lines :
                                if button[0:-2] == '_BUTTON_2_PRESS = ':
                                        if  self.comboBox.currentIndex() == 1:
                                                self.comboBox_2.clear()
                                                i = 0
                                                for key in _BUTTON_CODES:
                                                        self.comboBox_2.addItems(["{0}".format(key)])
                                                        i+=1
                                                        if int(button[-2]) > 0:
                                                                button_number = int(button[-2]) - 1
                                                                self.comboBox_2.setCurrentIndex(button_number)

                elif self.comboBox.currentIndex() == 0:
                        for button in file_lines :
                                if button[0:21] == "_BUTTON_2_KEYPRESS = ":

                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                self.comboBox_2.addItems(["{0}".format(key)])
                                                i+=1
                                        
                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                if key == button[21:-1]:
                                                        self.comboBox_2.setCurrentIndex(i)
                                                        break
                                                else:
                                                        i+=1
                                        break

###########################################################################################################


        if  self.comboBox_3.currentIndex() == 2:
                if self.comboBox.currentIndex() == 1:
                        for button in file_lines :
                                if button[0:-2] == '_BUTTON_3_PRESS = ':
                                        if  self.comboBox.currentIndex() == 1:
                                                self.comboBox_2.clear()
                                                i = 0
                                                for key in _BUTTON_CODES:
                                                        self.comboBox_2.addItems(["{0}".format(key)])
                                                        i+=1
                                                        if int(button[-2]) > 0:
                                                                button_number = int(button[-2]) - 1
                                                                self.comboBox_2.setCurrentIndex(button_number)

                elif self.comboBox.currentIndex() == 0:
                        for button in file_lines :
                                if button[0:21] == "_BUTTON_3_KEYPRESS = ":

                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                self.comboBox_2.addItems(["{0}".format(key)])
                                                i+=1
                                        
                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                if key == button[21:-1]:
                                                        self.comboBox_2.setCurrentIndex(i)
                                                        break
                                                else:
                                                        i+=1
                                        break

###########################################################################################################
                                                
        if  self.comboBox_3.currentIndex() == 3:
                if self.comboBox.currentIndex() == 1:
                        for button in file_lines :
                                if button[0:-2] == '_BUTTON_4_PRESS = ':
                                        if  self.comboBox.currentIndex() == 1:
                                                self.comboBox_2.clear()
                                                i = 0
                                                for key in _BUTTON_CODES:
                                                        self.comboBox_2.addItems(["{0}".format(key)])
                                                        i+=1
                                                        if int(button[-2]) > 0:
                                                                button_number = int(button[-2]) - 1
                                                                self.comboBox_2.setCurrentIndex(button_number)

                elif self.comboBox.currentIndex() == 0:
                        for button in file_lines :
                                if button[0:21] == "_BUTTON_4_KEYPRESS = ":

                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                self.comboBox_2.addItems(["{0}".format(key)])
                                                i+=1
                                        
                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                if key == button[21:-1]:
                                                        self.comboBox_2.setCurrentIndex(i)
                                                        break
                                                else:
                                                        i+=1
                                        break

###########################################################################################################

        if  self.comboBox_3.currentIndex() == 4:
                if self.comboBox.currentIndex() == 1:
                        for button in file_lines :
                                if button[0:-2] == '_BUTTON_5_PRESS = ':
                                        if  self.comboBox.currentIndex() == 1:
                                                self.comboBox_2.clear()
                                                i = 0
                                                for key in _BUTTON_CODES:
                                                        self.comboBox_2.addItems(["{0}".format(key)])
                                                        i+=1
                                                        if int(button[-2]) > 0:
                                                                button_number = int(button[-2]) - 1
                                                                self.comboBox_2.setCurrentIndex(button_number)

                elif self.comboBox.currentIndex() == 0:
                        for button in file_lines :
                                if button[0:21] == "_BUTTON_5_KEYPRESS = ":

                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                self.comboBox_2.addItems(["{0}".format(key)])
                                                i+=1
                                        
                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                if key == button[21:-1]:
                                                        self.comboBox_2.setCurrentIndex(i)
                                                        break
                                                else:
                                                        i+=1
                                        break

###########################################################################################################

        if  self.comboBox_3.currentIndex() == 5:
                if self.comboBox.currentIndex() == 1:
                        for button in file_lines :
                                if button[0:-2] == '_BUTTON_6_PRESS = ':
                                        if  self.comboBox.currentIndex() == 1:
                                                self.comboBox_2.clear()
                                                i = 0
                                                for key in _BUTTON_CODES:
                                                        self.comboBox_2.addItems(["{0}".format(key)])
                                                        i+=1
                                                        if int(button[-2]) > 0:
                                                                button_number = int(button[-2]) - 1
                                                                self.comboBox_2.setCurrentIndex(button_number)

                elif self.comboBox.currentIndex() == 0:
                        for button in file_lines :
                                if button[0:21] == "_BUTTON_6_KEYPRESS = ":

                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                self.comboBox_2.addItems(["{0}".format(key)])
                                                i+=1
                                        
                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                if key == button[21:-1]:
                                                        self.comboBox_2.setCurrentIndex(i)
                                                        break
                                                else:
                                                        i+=1
                                        break

###########################################################################################################

        if  self.comboBox_3.currentIndex() == 6:
                if self.comboBox.currentIndex() == 1:
                        for button in file_lines :
                                if button[0:-2] == '_BUTTON_7_PRESS = ':
                                        if  self.comboBox.currentIndex() == 1:
                                                self.comboBox_2.clear()
                                                i = 0
                                                for key in _BUTTON_CODES:
                                                        self.comboBox_2.addItems(["{0}".format(key)])
                                                        i+=1
                                                        if int(button[-2]) > 0:
                                                                button_number = int(button[-2]) - 1
                                                                self.comboBox_2.setCurrentIndex(button_number)

                elif self.comboBox.currentIndex() == 0:
                        for button in file_lines :
                                if button[0:21] == "_BUTTON_7_KEYPRESS = ":

                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                self.comboBox_2.addItems(["{0}".format(key)])
                                                i+=1
                                        
                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                if key == button[21:-1]:
                                                        self.comboBox_2.setCurrentIndex(i)
                                                        break
                                                else:
                                                        i+=1
                                        break


###########################################################################################################

        if  self.comboBox_3.currentIndex() == 7:
                if self.comboBox.currentIndex() == 1:
                        for button in file_lines :
                                if button[0:-2] == '_BUTTON_8_PRESS = ':
                                        if  self.comboBox.currentIndex() == 1:
                                                self.comboBox_2.clear()
                                                i = 0
                                                for key in _BUTTON_CODES:
                                                        self.comboBox_2.addItems(["{0}".format(key)])
                                                        i+=1
                                                        if int(button[-2]) > 0:
                                                                button_number = int(button[-2]) - 1
                                                                self.comboBox_2.setCurrentIndex(button_number)

                elif self.comboBox.currentIndex() == 0:
                        for button in file_lines :
                                if button[0:21] == "_BUTTON_8_KEYPRESS = ":

                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                self.comboBox_2.addItems(["{0}".format(key)])
                                                i+=1
                                        
                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                if key == button[21:-1]:
                                                        self.comboBox_2.setCurrentIndex(i)
                                                        break
                                                else:
                                                        i+=1
                                        break


###########################################################################################################

        if  self.comboBox_3.currentIndex() == 8:
                if self.comboBox.currentIndex() == 1:
                        for button in file_lines :
                                if button[0:-2] == '_BUTTON_9_PRESS = ':
                                        if  self.comboBox.currentIndex() == 1:
                                                self.comboBox_2.clear()
                                                i = 0
                                                for key in _BUTTON_CODES:
                                                        self.comboBox_2.addItems(["{0}".format(key)])
                                                        i+=1
                                                        if int(button[-2]) > 0:
                                                                button_number = int(button[-2]) - 1
                                                                self.comboBox_2.setCurrentIndex(button_number)

                elif self.comboBox.currentIndex() == 0:
                        for button in file_lines :
                                if button[0:21] == "_BUTTON_9_KEYPRESS = ":

                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                self.comboBox_2.addItems(["{0}".format(key)])
                                                i+=1
                                        
                                        i=0
                                        for key in _KEYBOARD_CODES:
                                                if key == button[21:-1]:
                                                        self.comboBox_2.setCurrentIndex(i)
                                                        break
                                                else:
                                                        i+=1
                                        break


###########################################################################################################

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
